"""Generate the embedded 128x128 RGB565 face-pipeline test fixture."""

from pathlib import Path

import numpy as np
from PIL import Image
from skimage import data


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "Src" / "app" / "face_debug_image.c"


def main() -> None:
    image = Image.fromarray(data.astronaut()).resize((128, 128), Image.Resampling.LANCZOS)
    rgb = np.asarray(image, dtype=np.uint16)
    packed = ((rgb[:, :, 0] >> 3) << 11) | ((rgb[:, :, 1] >> 2) << 5) | (rgb[:, :, 2] >> 3)
    values = packed.reshape(-1)
    lines = []
    for offset in range(0, len(values), 12):
        lines.append("  " + ", ".join(f"0x{value:04x}" for value in values[offset:offset + 12]) + ",")

    OUTPUT.write_text(
        "/* Generated by Model/generate-face-debug-fixture.py. */\n"
        "#include \"app/face_debug_image.h\"\n\n"
        "const uint16_t g_face_debug_image_rgb565[FACE_DEBUG_IMAGE_WIDTH *\n"
        "                                                FACE_DEBUG_IMAGE_HEIGHT] = {\n"
        + "\n".join(lines)
        + "\n};\n",
        encoding="ascii",
    )


if __name__ == "__main__":
    main()
