################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/pele/Documents/GitHub/ObjectDet/Src/app_cam.c \
C:/Users/pele/Documents/GitHub/ObjectDet/Src/app_fuseprogramming.c \
C:/Users/pele/Documents/GitHub/ObjectDet/Src/app_postprocess.c \
C:/Users/pele/Documents/GitHub/ObjectDet/Src/crop_img.c \
C:/Users/pele/Documents/GitHub/ObjectDet/Src/main.c \
C:/Users/pele/Documents/GitHub/ObjectDet/Middlewares/AI_Runtime/Npu/Devices/STM32N6XX/mcu_cache.c \
C:/Users/pele/Documents/GitHub/ObjectDet/Model/network.c \
C:/Users/pele/Documents/GitHub/ObjectDet/Middlewares/AI_Runtime/Npu/Devices/STM32N6XX/npu_cache.c \
C:/Users/pele/Documents/GitHub/ObjectDet/Src/pc_stream.c \
C:/Users/pele/Documents/GitHub/ObjectDet/Src/stm32_lcd_ex.c \
C:/Users/pele/Documents/GitHub/ObjectDet/Src/stm32n6xx_it.c \
C:/Users/pele/Documents/GitHub/ObjectDet/Src/syscalls.c 

OBJS += \
./Application/app_cam.o \
./Application/app_fuseprogramming.o \
./Application/app_postprocess.o \
./Application/crop_img.o \
./Application/main.o \
./Application/mcu_cache.o \
./Application/network.o \
./Application/npu_cache.o \
./Application/pc_stream.o \
./Application/stm32_lcd_ex.o \
./Application/stm32n6xx_it.o \
./Application/syscalls.o 

C_DEPS += \
./Application/app_cam.d \
./Application/app_fuseprogramming.d \
./Application/app_postprocess.d \
./Application/crop_img.d \
./Application/main.d \
./Application/mcu_cache.d \
./Application/network.d \
./Application/npu_cache.d \
./Application/pc_stream.d \
./Application/stm32_lcd_ex.d \
./Application/stm32n6xx_it.d \
./Application/syscalls.d 


# Each subdirectory must supply rules for building sources it contributes
Application/app_cam.o: C:/Users/pele/Documents/GitHub/ObjectDet/Src/app_cam.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/app_fuseprogramming.o: C:/Users/pele/Documents/GitHub/ObjectDet/Src/app_fuseprogramming.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/app_postprocess.o: C:/Users/pele/Documents/GitHub/ObjectDet/Src/app_postprocess.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/crop_img.o: C:/Users/pele/Documents/GitHub/ObjectDet/Src/crop_img.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/main.o: C:/Users/pele/Documents/GitHub/ObjectDet/Src/main.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/mcu_cache.o: C:/Users/pele/Documents/GitHub/ObjectDet/Middlewares/AI_Runtime/Npu/Devices/STM32N6XX/mcu_cache.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/network.o: C:/Users/pele/Documents/GitHub/ObjectDet/Model/network.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/npu_cache.o: C:/Users/pele/Documents/GitHub/ObjectDet/Middlewares/AI_Runtime/Npu/Devices/STM32N6XX/npu_cache.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/pc_stream.o: C:/Users/pele/Documents/GitHub/ObjectDet/Src/pc_stream.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/stm32_lcd_ex.o: C:/Users/pele/Documents/GitHub/ObjectDet/Src/stm32_lcd_ex.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/stm32n6xx_it.o: C:/Users/pele/Documents/GitHub/ObjectDet/Src/stm32n6xx_it.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/syscalls.o: C:/Users/pele/Documents/GitHub/ObjectDet/Src/syscalls.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application

clean-Application:
	-$(RM) ./Application/app_cam.cyclo ./Application/app_cam.d ./Application/app_cam.o ./Application/app_cam.su ./Application/app_fuseprogramming.cyclo ./Application/app_fuseprogramming.d ./Application/app_fuseprogramming.o ./Application/app_fuseprogramming.su ./Application/app_postprocess.cyclo ./Application/app_postprocess.d ./Application/app_postprocess.o ./Application/app_postprocess.su ./Application/crop_img.cyclo ./Application/crop_img.d ./Application/crop_img.o ./Application/crop_img.su ./Application/main.cyclo ./Application/main.d ./Application/main.o ./Application/main.su ./Application/mcu_cache.cyclo ./Application/mcu_cache.d ./Application/mcu_cache.o ./Application/mcu_cache.su ./Application/network.cyclo ./Application/network.d ./Application/network.o ./Application/network.su ./Application/npu_cache.cyclo ./Application/npu_cache.d ./Application/npu_cache.o ./Application/npu_cache.su ./Application/pc_stream.cyclo ./Application/pc_stream.d ./Application/pc_stream.o ./Application/pc_stream.su ./Application/stm32_lcd_ex.cyclo ./Application/stm32_lcd_ex.d ./Application/stm32_lcd_ex.o ./Application/stm32_lcd_ex.su ./Application/stm32n6xx_it.cyclo ./Application/stm32n6xx_it.d ./Application/stm32n6xx_it.o ./Application/stm32n6xx_it.su ./Application/syscalls.cyclo ./Application/syscalls.d ./Application/syscalls.o ./Application/syscalls.su

.PHONY: clean-Application

